name: tlenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - gast=0.4.0=py_0
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py37hf8bcb03_0
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2020.1=217
  - joblib=0.15.1=py_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.11.4=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.1.1=py37_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pip=20.0.2=py37_3
  - protobuf=3.11.4=py37he6710b0_0
  - python=3.7.7=hcff3b4d_5
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=46.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=gpu_py37h4491b45_0
  - tensorflow-base=1.14.0=gpu_py37h8d69cac_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - audioread==2.1.9
    - cffi==1.14.5
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==5.0.9
    - idna==2.10
    - keras==2.3.1
    - keras-lr-multiplier==0.8.0
    - keras-tcn==3.1.0
    - kiwisolver==1.3.1
    - librosa==0.8.1
    - llvmlite==0.36.0
    - matplotlib==3.4.2
    - numba==0.53.1
    - packaging==20.9
    - pandas==1.2.4
    - patsy==0.5.1
    - pickle5==0.0.11
    - pillow==8.2.0
    - pooch==1.3.0
    - pycparser==2.20
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.3.1
    - requests==2.25.1
    - resampy==0.2.2
    - soundfile==0.10.3.post1
    - statsmodels==0.12.2
    - urllib3==1.26.5
